name = "Simply Creative"
author = "Ocawesome101"
version = "0.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b230e0160889c5e46a5fac41e192751834a504792e4e5a934bb37878de4a44b1"

[versions]
forge = "40.1.70"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
