name = "Simply Creative"
author = "Ocawesome101"
version = "0.6.0-pre2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c36b086c637641c748024778910999a5a725315b475a2286c0d181a014b0d58d"

[versions]
forge = "40.2.2"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
