name = "Simply Creative"
author = "Ocawesome101"
version = "0.6.0-pre"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60e196639ec106d0756b0ba696404e8c90fbf0cfd4099d3a75eb71ebafe91089"

[versions]
forge = "40.2.2"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
