name = "Simply Creative"
author = "Ocawesome101"
version = "0.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6cd309baff44ba578334f4f21ab674d373402da53c0b049a6fc6fb6357376f53"

[versions]
forge = "40.1.70"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
