name = "Simply Creative"
author = "Ocawesome101"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "098b758c1838028e68bd213dc85044afe08d08f0cfdfac7ee471f3b9de32162e"

[versions]
forge = "40.1.68"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
