name = "Simply Creative"
author = "Ocawesome101"
version = "0.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4b211af86acd5c7fab1fca970da98782d03ab470e44bfb61e98aee72bffa18d"

[versions]
forge = "40.1.68"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
