name = "Simply Creative"
author = "Ocawesome101"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d013cae661172aa4b4732ce5f5b362f281a2d6494235d86de6e617f1932bb43"

[versions]
forge = "40.1.68"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
